[[main]]
none = "none"

[[main]]
name = "Posts"
pageRef = "/posts/"
identifier = "FklCsWfFBC"
weight = 1

[[main]]
name = "About"
pageRef = "/about/"
identifier = "sXwR6bnD9Y"
weight = 9_999

[[footer]]
none = "none"

[[footer]]
name = "Categories"
pageRef = "/categories/"
identifier = "gwp7KrM8rn"
weight = 2

[[footer]]
name = "Series"
pageRef = "/series/"
identifier = "gApDl8ceTw"
weight = 1
